### PR TITLE
Translation for pt-br

### PR DESCRIPTION
**Pull request by ruanltbg**
It still ongoing @allanesquina, please wait for my signal to review ;)

I saw that @ivanbanov said that he would translate, but in his fork has no work done yet, so I was with free time and took the chance, sorry for did not ask to translate. I hope that @ivanbanov do not get angry with me.

@allanesquina could you explain to me how to generate the final HTML?

**Please do not merge yet**

### CODE REVIEW

**Comment by allanesquina** [comment]
No problem, to generate the static files you can use:

    grunt dist

or to development
    
    grunt server

I'm waiting for you signal @ruanltbg! Thanks! :+1:

**Comment by ivanbanov** [comment]
No worries dude! It's ok! lets finish it

**Comment by ruanltbg** [comment]
@allanesquina I tried

```bash
∴ npm install -g grunt-cli
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

∴ npm install
grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── lodash@2.4.2
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, qs@0.5.6, noptify@0.0.3)
└── gaze@0.5.1 (globule@0.1.0)

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── nopt@1.0.10 (abbrev@1.0.7)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

grunt-contrib-connect@0.9.0 node_modules/grunt-contrib-connect
├── opn@1.0.2
├── connect-livereload@0.5.3
├── async@0.9.2
├── portscanner@1.0.0 (async@0.1.15)
└── connect@2.30.1 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, cookie-signature@1.0.6, pause@0.1.0, fresh@0.3.0, response-time@2.3.1, vhost@3.0.1, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, parseurl@1.3.0, cookie-parser@1.3.5, depd@1.0.1, qs@4.0.0, http-errors@1.3.1, serve-favicon@2.3.0, connect-timeout@1.6.2, debug@2.2.0, method-override@2.3.4, finalhandler@0.4.0, morgan@1.6.1, body-parser@1.13.2, express-session@1.11.3, multiparty@3.3.2, type-is@1.6.5, serve-index@1.7.1, errorhandler@1.4.1, compression@1.5.1, csurf@1.8.3, serve-static@1.10.0)

grunt-contrib-cssmin@0.9.0 node_modules/grunt-contrib-cssmin
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── clean-css@2.1.8 (commander@2.1.0)
└── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

grunt-contrib-uglify@0.4.1 node_modules/grunt-contrib-uglify
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
└── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

```
Then
```bash
∴ grunt server
Running "connect:server" (connect) task
Started connect web server on http://0.0.0.0:8000

Running "watch" task
Waiting...
Warning: EMFILE: Too many opened files.

Running "watch" task
Waiting...
Warning: EMFILE, too many open files
.......
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
......
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
```
And the dist:
```bash
∴ grunt dist
Warning: Task "dist" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by ruanltbg** [comment]
@allanesquina and @ivanbanov could you guys review?

**Comment by allanesquina** [comment]
Yup, thanks @ruanltbg! :+1:

**Pull request merged**
