### PR TITLE
add arabic translation (partial)

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by allanesquina** [comment]
Hey @atefBB, welcome. thanks :+1: 
Can I merge it?

**Comment by atefBB** [comment]
hey ! Yes PLZ !

**Comment by allanesquina** [comment]
Looking forward to see that translation, thx :+1:

**Comment by atefBB** [comment]
I'm working on it, I'll do my BEST ! thx.

**Comment by gnuwilliam** [comment]
That's pretty awesome @atefBB! Thank you for taking this task. Keep up the good work!

**Comment by atefBB** [comment]
thx @gnuwilliam ! I'll do my best (In Shaa Allah).

**Pull request merged**
