### PR TITLE
remove backbone weekly link.

### PR DESCRIPTION
**Pull request by appleboy**
http://backboneweekly.com/

Redirect to godaddy.com, please check again.

### CODE REVIEW

**Comment by allanesquina** [comment]
Maybe it's a temporary server instability, let's wait for a few more days, ok? 
Thanks @appleboy :+1:

**Comment by appleboy** [comment]
@allanesquina OK ..

**Comment by allanesquina** [comment]
Hi @appleboy, can you resolve the conflicts please? I'll merge this pull request. Thanks :+1:

**Comment by appleboy** [comment]
@allanesquina Done!

**Comment by allanesquina** [comment]
Thanks :+1:

**Pull request merged**
