### PR TITLE
Russian translation ru-ru =)

### PR DESCRIPTION
**Pull request by vvscode**
Cover #241 

### What to do

- [x] Initiate ru-ru structure
- [x] Translate `ru-ru.json`
- [x] Translate `partials/code-style.html`
- [x] Translate `partials/getting-started.html`
- [x] Translate `partials/good-parts.html`
- [x] Translate `partials/licence.html`
- [x] Translate `partials/patterns.html`
- [x] Translate `partials/testing-tools.html`
- [x] Translate `partials/welcome.html`

@allanesquina  should I add links to resources on russian? or just tranlate existing resources?

### CODE REVIEW

**Comment by vvscode** [comment]
Related to #241

**Comment by allanesquina** [comment]
Welcome @vvscode, I'm glad to see your work!
Looking forward to see that in production. 
Thank you very much :+1:

**Comment by vvscode** [comment]
@allanesquina  looks like done

**Comment by allanesquina** [comment]
Man, awesome, I'm gonna make some tests and deploy this changes.
@vvscode Well done :+1:

**Pull request merged**
