### PR TITLE
Add link to the best article about learning JS currently

### PR DESCRIPTION
**Pull request by leobetosouza**
Because @jugoncalves is awesome

### CODE REVIEW

**Comment by allanesquina** [comment]
I agree with you about @jugoncalves, but in my opinion, this link is for another guide and not for an specific subject. The proposal of this project is to be a guide, Isn't?

**Comment by raphaelpor** [comment]
Nice article. But I agree with @allanesquina.

**Comment by jugoncalves** [comment]
While I agree that the post is a guide on learning JavaScript and may not be a good fit, there's already a JS guide featured (["How to Learn JavaScript Properly" by JavaScript is Sexy](http://www.jstherightway.org/#reading)).

And thank you, @leobetosouza :heart:

**Comment by leobetosouza** [comment]
This link was added just after the js is sexy guide and I think that both are good resources to read.

I added it just on the section of good articles to read... if this article is not worthy to be here, I do not know what would.

**Comment by allanesquina** [comment]
Ok guys, I'm just trying to filter duplicate information. 
Thanks @leobetosouza and @jugoncalves :+1:

**Comment by leobetosouza** [comment]
@allanesquina peace and love ;)

**Pull request merged**
