### PR TITLE
Switch license to CC BY-SA 3.0

### PR DESCRIPTION
**Pull request by Calinou**
This is a pull request that switches to a free culture license.

### CODE REVIEW

**Comment by allanesquina** [comment]
Hi @Calinou, thanks but this project is a non commercial project.

**Comment by Calinou** [comment]
You may want to read [this essay](freedomdefined.org/Licenses/NC).

**Comment by allanesquina** [comment]
Right, we must study better the case.

**Comment by allanesquina** [comment]
Closing for while!

**Pull request closed without merging**
